spring.application.name=weather-monitoring-app-2
spring.datasource.url=jdbc:postgresql://localhost:5432/weather_db
spring.datasource.username=########
spring.datasource.password=#####
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
openweathermap.api.key=#########
